server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的服务名称
    cloud:
      config:
        server:
          git:
            skipSslValidation: true # 跳过ssl认证
            uri: https://github.com/wang-so/springcloud-config.git  #GitHub上复制的项目地址
            search-paths:  #搜索目录
              - springcloud-config
        label: master   #读取分支
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/